on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to server
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          cd ${{ secrets.SSH_APP_PATH }}
          git pull
          docker build -t bloky.nl .
          docker kill bloky.nl
          docker rm bloky.nl
          docker run --restart unless-stopped --name bloky.nl -p 3000:3000 -d bloky.nl                  
          ENDSSH